### ISSUE TITLE
Compatibility for Windows

### ISSUE THREAD

**Issue by fairyhunter13** [amplitude/experiment-go-server#2]
Hello, I want to request the compatibility option for Windows. Is it possible?

**Comment by fairyhunter13** [comment]
@bgiori Ok, thank you for your help and contributions. I appreciate them.

**Comment by vipulkv** [comment]
Hi @bgiori - do you have any update on this? This issue was opened around 1.5 years ago.

**Comment by bgiori** [comment]
Windows is now compatible in v1.3.0
